aliyun:
  oss:
    endpoint: http://oss-cn-beijing.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI4Fwq74wC7BeReHcD7YDU # 访问身份验证中用到用户标识
    accessKeySecret: legRFtwEsgu9DESSPpEWOS5RJaNwdP # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketVideo: yuans-video-res # oss的存储空间
    bucketImg: yuans-video # oss的存储空间
