server:
        port: 8081

spring:
        # Spring Security 配置项，对应 SecurityProperties 配置类
        security:
                # 配置默认的 InMemoryUserDetailsManager 的用户账号与密码。
                user:
                        name: user # 账号
                        password: user # 密码
                        roles: ADMIN # 拥有角色

# token配置
token:
        # 令牌有效期（默认30分钟）
        expireTime: 30
        # 令牌秘钥
        secret: abcdefghijklmnopqrstuvwxyz
        # 令牌自定义标识
        header: Authorization